import { HTTP_STATUS, ERROR_TYPES, PROBLEM_TYPES, RETRY_CONFIG } from "@/shared/constants";

/**
 * RFC 9457 Problem Details for HTTP APIs
 * https://datatracker.ietf.org/doc/html/rfc9457
 */

/**
 * RFC 9457 Problem Details interface
 * Updated from RFC 7807 to RFC 9457 specification
 */
export interface ProblemDetail {
  /** A URI reference that identifies the problem type */
  type?: string;
  /** A short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code generated by the origin server */
  status?: number;
  /** A human-readable explanation specific to this occurrence */
  detail?: string;
  /** A URI reference that identifies the specific occurrence */
  instance?: string;
  /** Extension members (any additional properties) */
  [key: string]: unknown;
}

/**
 * Enhanced error types with RFC 9457 compliance
 */
export type AppErrorType = (typeof ERROR_TYPES)[keyof typeof ERROR_TYPES];

/**
 * Enhanced AppError interface with RFC 9457 Problem Details
 */
export interface AppError extends ProblemDetail {
  /** Categorized error type for application logic */
  errorType: AppErrorType;
  /** Original error message */
  message: string;
  /** HTTP status code */
  status?: number;
  /** Error code from server or client */
  code?: string | number;
  /** Additional error details */
  details?: any;
  /** Request correlation ID */
  requestId?: string;
  /** Whether the error is retryable */
  retryable?: boolean;
  /** Original error cause */
  cause?: unknown;
  /** Validation field errors */
  fieldErrors?: Record<string, string[]>;
  /** Retry configuration */
  retryConfig?: RetryConfig;
}

/**
 * Retry configuration for different error types
 */
export interface RetryConfig {
  /** Maximum number of retry attempts */
  maxAttempts: number;
  /** Base delay in milliseconds */
  baseDelay: number;
  /** Maximum delay in milliseconds */
  maxDelay: number;
  /** Exponential backoff multiplier */
  backoffMultiplier: number;
  /** Jitter factor (0-1) to add randomness */
  jitterFactor: number;
  /** HTTP status codes that should trigger retry */
  retryableStatusCodes: readonly number[];
}

/**
 * Default retry configurations by error type
 */
export const DEFAULT_RETRY_CONFIGS: Record<AppErrorType, RetryConfig | null> = {
  [ERROR_TYPES.NETWORK]: RETRY_CONFIG.NETWORK,
  [ERROR_TYPES.TIMEOUT]: RETRY_CONFIG.TIMEOUT,
  [ERROR_TYPES.RATE_LIMIT]: RETRY_CONFIG.RATE_LIMIT,
  [ERROR_TYPES.SERVER]: RETRY_CONFIG.SERVER,
  [ERROR_TYPES.CANCELED]: null,
  [ERROR_TYPES.AUTH]: null,
  [ERROR_TYPES.VALIDATION]: null,
  [ERROR_TYPES.CLIENT]: null,
  [ERROR_TYPES.UNKNOWN]: null,
};

/**
 * Standard problem types as per RFC 9457
 */
export { PROBLEM_TYPES } from "@/shared/constants";

/**
 * Create a RFC 9457 compliant Problem Detail object
 */
export function createProblemDetail(
  type: string,
  title: string,
  status?: number,
  detail?: string,
  instance?: string,
  extensions?: Record<string, unknown>,
): ProblemDetail {
  const problem: ProblemDetail = {
    type,
    title,
    ...(status !== undefined && { status }),
    ...(detail && { detail }),
    ...(instance && { instance }),
    ...extensions,
  };

  return problem;
}

/**
 * Validate a Problem Detail object according to RFC 9457
 */
export function validateProblemDetail(problem: unknown): problem is ProblemDetail {
  if (!problem || typeof problem !== "object" || Array.isArray(problem)) {
    return false;
  }

  const p = problem as Record<string, unknown>;

  // Type must be a string URI if present
  if (p.type !== undefined && typeof p.type !== "string") {
    return false;
  }

  // Title must be a string if present
  if (p.title !== undefined && typeof p.title !== "string") {
    return false;
  }

  // Status must be a number if present
  if (p.status !== undefined && typeof p.status !== "number") {
    return false;
  }

  // Detail must be a string if present
  if (p.detail !== undefined && typeof p.detail !== "string") {
    return false;
  }

  // Instance must be a string URI if present
  if (p.instance !== undefined && typeof p.instance !== "string") {
    return false;
  }

  return true;
}

/**
 * Extract extension members from a Problem Detail object
 */
export function extractExtensionMembers(problem: ProblemDetail): Record<string, unknown> {
  const standardMembers = new Set(["type", "title", "status", "detail", "instance"]);
  const extensions: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(problem)) {
    if (!standardMembers.has(key)) {
      extensions[key] = value;
    }
  }

  return extensions;
}

/**
 * Enhanced error type detection patterns
 */
interface ErrorPattern {
  statusCodes?: readonly number[];
  messagePatterns?: readonly RegExp[];
  codes?: readonly string[];
  typePatterns?: readonly string[];
  hasFieldErrors?: boolean;
}

export const ERROR_PATTERNS: Record<string, ErrorPattern> = {
  [ERROR_TYPES.AUTH]: {
    statusCodes: [HTTP_STATUS.UNAUTHORIZED, HTTP_STATUS.FORBIDDEN] as const,
    messagePatterns: [
      /unauthorized/i,
      /authentication/i,
      /access.*denied/i,
      /forbidden/i,
      /invalid.*token/i,
      /expired.*token/i,
    ] as const,
    typePatterns: [
      PROBLEM_TYPES.AUTHENTICATION_REQUIRED,
      PROBLEM_TYPES.AUTHORIZATION_FAILED,
    ] as const,
  },
  [ERROR_TYPES.VALIDATION]: {
    statusCodes: [HTTP_STATUS.BAD_REQUEST, HTTP_STATUS.UNPROCESSABLE_ENTITY] as const,
    messagePatterns: [
      /validation/i,
      /invalid.*input/i,
      /bad.*request/i,
      /constraint.*violation/i,
    ] as const,
    typePatterns: [PROBLEM_TYPES.VALIDATION_ERROR] as const,
    hasFieldErrors: true,
  },
  [ERROR_TYPES.TIMEOUT]: {
    statusCodes: [408] as const,
    messagePatterns: [/timeout/i, /timed.*out/i] as const,
    codes: ["ECONNABORTED", "ETIMEDOUT"] as const,
    typePatterns: [PROBLEM_TYPES.TIMEOUT_ERROR] as const,
  },
  [ERROR_TYPES.NETWORK]: {
    messagePatterns: [/network/i, /connection/i, /econnrefused/i] as const,
    codes: ["ECONNREFUSED", "ENOTFOUND", "ECONNRESET"] as const,
    typePatterns: [PROBLEM_TYPES.NETWORK_ERROR] as const,
  },
  [ERROR_TYPES.RATE_LIMIT]: {
    statusCodes: [HTTP_STATUS.TOO_MANY_REQUESTS] as const,
    messagePatterns: [/rate.*limit/i, /too.*many.*requests/i] as const,
    typePatterns: [PROBLEM_TYPES.RATE_LIMIT_EXCEEDED] as const,
  },
  [ERROR_TYPES.SERVER]: {
    statusCodes: [
      HTTP_STATUS.INTERNAL_SERVER_ERROR,
      HTTP_STATUS.BAD_GATEWAY,
      HTTP_STATUS.SERVICE_UNAVAILABLE,
      HTTP_STATUS.GATEWAY_TIMEOUT,
    ] as const,
    messagePatterns: [/server.*error/i, /internal.*error/i] as const,
    typePatterns: [PROBLEM_TYPES.SERVER_ERROR] as const,
  },
};

/**
 * Determine error type based on enhanced patterns
 */
export function determineErrorType(
  status?: number,
  message?: string,
  code?: string,
  type?: string,
  hasFieldErrors = false,
): AppErrorType {
  // Check each error pattern
  for (const [errorType, pattern] of Object.entries(ERROR_PATTERNS)) {
    // Check status codes
    if (status && pattern.statusCodes?.includes(status)) {
      // Special case for validation: check if it has field errors
      if (errorType === "validation" && pattern.hasFieldErrors && !hasFieldErrors) {
        continue;
      }
      return errorType as AppErrorType;
    }

    // Check message patterns
    if (message && pattern.messagePatterns) {
      for (const regex of pattern.messagePatterns) {
        if (regex.test(message)) {
          return errorType as AppErrorType;
        }
      }
    }

    // Check error codes
    if (code && pattern.codes?.includes(code)) {
      return errorType as AppErrorType;
    }

    // Check problem type patterns
    if (type && pattern.typePatterns?.includes(type)) {
      return errorType as AppErrorType;
    }
  }

  // Fallback logic
  if (status) {
    if (status >= HTTP_STATUS.BAD_REQUEST && status < HTTP_STATUS.INTERNAL_SERVER_ERROR) {
      return ERROR_TYPES.CLIENT;
    }
    if (status >= HTTP_STATUS.INTERNAL_SERVER_ERROR && status < 600) {
      return ERROR_TYPES.SERVER;
    }
  }

  return ERROR_TYPES.UNKNOWN;
}

/**
 * Calculate retry delay with exponential backoff and jitter
 */
export function calculateRetryDelay(attempt: number, config: RetryConfig): number {
  const exponentialDelay = config.baseDelay * config.backoffMultiplier ** (attempt - 1);
  const cappedDelay = Math.min(exponentialDelay, config.maxDelay);

  // Add jitter to prevent thundering herd
  const jitter = cappedDelay * config.jitterFactor * Math.random();

  return Math.floor(cappedDelay + jitter);
}

/**
 * Check if an error should be retried
 */
export function shouldRetryError(error: AppError, attempt: number): boolean {
  if (!error.retryable || !error.retryConfig) {
    return false;
  }

  if (attempt > error.retryConfig.maxAttempts) {
    return false;
  }

  // Check if status code is retryable
  if (error.status && error.retryConfig.retryableStatusCodes.length > 0) {
    return error.retryConfig.retryableStatusCodes.includes(error.status);
  }

  return true;
}
