export const ENV_KEYS = [
  "VITE_API_URL_SERVER",
  "VITE_AUTH_DOMAIN_AUTH",
  "VITE_AUTH_DOMAIN_APP",
  "VITE_AUTH_REDIRECT_AFTER_LOGIN",
  "VITE_AUTH_REDIRECT_AFTER_LOGOUT",
  "VITE_AUTH_REDIRECT_AFTER_SIGNUP",
  "VITE_ENABLE_MSW",
  "VITE_LOG_LEVEL",
] as const;

export type EnvKey = (typeof ENV_KEYS)[number];
