export const ENV_KEYS = [
  "VITE_API_URL_SERVER",
  "VITE_AUTH_DOMAIN_AUTH",
  "VITE_AUTH_DOMAIN_APP",
  "VITE_AUTH_REDIRECT_AFTER_LOGIN",
  "VITE_AUTH_REDIRECT_AFTER_LOGOUT",
  "VITE_AUTH_REDIRECT_AFTER_SIGNUP",
  "VITE_ENABLE_MSW",
  "VITE_LOG_LEVEL",
  // Payment provider configuration
  "VITE_STRIPE_PUBLISHABLE_KEY",
  "VITE_PAYPAL_CLIENT_ID",
  "VITE_PAYPAL_CLIENT_SECRET",
  "VITE_ENVIRONMENT",
] as const;

export type EnvKey = (typeof ENV_KEYS)[number];
