/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as UsersRouteImport } from "./pages/users"
import { Route as UserPreferencesRouteImport } from "./pages/user-preferences"
import { Route as SubscriptionsRouteImport } from "./pages/subscriptions"
import { Route as PreferencesDemoRouteImport } from "./pages/preferences-demo"
import { Route as GatewayConfigRouteImport } from "./pages/gateway-config"
import { Route as ExamplesRouteImport } from "./pages/examples"
import { Route as DashboardRouteImport } from "./pages/dashboard"
import { Route as CrmFollowUpsRouteImport } from "./pages/crm-follow-ups"
import { Route as CrmDashboardRouteImport } from "./pages/crm-dashboard"
import { Route as CheckoutRouteImport } from "./pages/checkout"
import { Route as BillingRouteImport } from "./pages/billing"
import { Route as AboutRouteImport } from "./pages/about"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as CrmPipelineRouteImport } from "./pages/crm.pipeline"
import { Route as CrmLeadsRouteImport } from "./pages/crm.leads"
import { Route as CrmContactsRouteImport } from "./pages/crm.contacts"
import { Route as CrmLeadsLeadIdRouteImport } from "./pages/crm.leads.$leadId"
import { Route as CrmContactsContactIdRouteImport } from "./pages/crm.contacts.$contactId"

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any)
const UserPreferencesRoute = UserPreferencesRouteImport.update({
  id: "/user-preferences",
  path: "/user-preferences",
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: "/subscriptions",
  path: "/subscriptions",
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesDemoRoute = PreferencesDemoRouteImport.update({
  id: "/preferences-demo",
  path: "/preferences-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayConfigRoute = GatewayConfigRouteImport.update({
  id: "/gateway-config",
  path: "/gateway-config",
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: "/examples",
  path: "/examples",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmFollowUpsRoute = CrmFollowUpsRouteImport.update({
  id: "/crm-follow-ups",
  path: "/crm-follow-ups",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDashboardRoute = CrmDashboardRouteImport.update({
  id: "/crm-dashboard",
  path: "/crm-dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: "/crm/pipeline",
  path: "/crm/pipeline",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: "/crm/leads",
  path: "/crm/leads",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: "/crm/contacts",
  path: "/crm/contacts",
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsLeadIdRoute = CrmLeadsLeadIdRouteImport.update({
  id: "/$leadId",
  path: "/$leadId",
  getParentRoute: () => CrmLeadsRoute,
} as any)
const CrmContactsContactIdRoute = CrmContactsContactIdRouteImport.update({
  id: "/$contactId",
  path: "/$contactId",
  getParentRoute: () => CrmContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/billing": typeof BillingRoute
  "/checkout": typeof CheckoutRoute
  "/crm-dashboard": typeof CrmDashboardRoute
  "/crm-follow-ups": typeof CrmFollowUpsRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/gateway-config": typeof GatewayConfigRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
  "/crm/contacts": typeof CrmContactsRouteWithChildren
  "/crm/leads": typeof CrmLeadsRouteWithChildren
  "/crm/pipeline": typeof CrmPipelineRoute
  "/crm/contacts/$contactId": typeof CrmContactsContactIdRoute
  "/crm/leads/$leadId": typeof CrmLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/billing": typeof BillingRoute
  "/checkout": typeof CheckoutRoute
  "/crm-dashboard": typeof CrmDashboardRoute
  "/crm-follow-ups": typeof CrmFollowUpsRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/gateway-config": typeof GatewayConfigRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
  "/crm/contacts": typeof CrmContactsRouteWithChildren
  "/crm/leads": typeof CrmLeadsRouteWithChildren
  "/crm/pipeline": typeof CrmPipelineRoute
  "/crm/contacts/$contactId": typeof CrmContactsContactIdRoute
  "/crm/leads/$leadId": typeof CrmLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/billing": typeof BillingRoute
  "/checkout": typeof CheckoutRoute
  "/crm-dashboard": typeof CrmDashboardRoute
  "/crm-follow-ups": typeof CrmFollowUpsRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/gateway-config": typeof GatewayConfigRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
  "/crm/contacts": typeof CrmContactsRouteWithChildren
  "/crm/leads": typeof CrmLeadsRouteWithChildren
  "/crm/pipeline": typeof CrmPipelineRoute
  "/crm/contacts/$contactId": typeof CrmContactsContactIdRoute
  "/crm/leads/$leadId": typeof CrmLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/about"
    | "/billing"
    | "/checkout"
    | "/crm-dashboard"
    | "/crm-follow-ups"
    | "/dashboard"
    | "/examples"
    | "/gateway-config"
    | "/preferences-demo"
    | "/subscriptions"
    | "/user-preferences"
    | "/users"
    | "/crm/contacts"
    | "/crm/leads"
    | "/crm/pipeline"
    | "/crm/contacts/$contactId"
    | "/crm/leads/$leadId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/about"
    | "/billing"
    | "/checkout"
    | "/crm-dashboard"
    | "/crm-follow-ups"
    | "/dashboard"
    | "/examples"
    | "/gateway-config"
    | "/preferences-demo"
    | "/subscriptions"
    | "/user-preferences"
    | "/users"
    | "/crm/contacts"
    | "/crm/leads"
    | "/crm/pipeline"
    | "/crm/contacts/$contactId"
    | "/crm/leads/$leadId"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/about"
    | "/billing"
    | "/checkout"
    | "/crm-dashboard"
    | "/crm-follow-ups"
    | "/dashboard"
    | "/examples"
    | "/gateway-config"
    | "/preferences-demo"
    | "/subscriptions"
    | "/user-preferences"
    | "/users"
    | "/crm/contacts"
    | "/crm/leads"
    | "/crm/pipeline"
    | "/crm/contacts/$contactId"
    | "/crm/leads/$leadId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  CheckoutRoute: typeof CheckoutRoute
  CrmDashboardRoute: typeof CrmDashboardRoute
  CrmFollowUpsRoute: typeof CrmFollowUpsRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  GatewayConfigRoute: typeof GatewayConfigRoute
  PreferencesDemoRoute: typeof PreferencesDemoRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  UserPreferencesRoute: typeof UserPreferencesRoute
  UsersRoute: typeof UsersRoute
  CrmContactsRoute: typeof CrmContactsRouteWithChildren
  CrmLeadsRoute: typeof CrmLeadsRouteWithChildren
  CrmPipelineRoute: typeof CrmPipelineRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/user-preferences": {
      id: "/user-preferences"
      path: "/user-preferences"
      fullPath: "/user-preferences"
      preLoaderRoute: typeof UserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/subscriptions": {
      id: "/subscriptions"
      path: "/subscriptions"
      fullPath: "/subscriptions"
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preferences-demo": {
      id: "/preferences-demo"
      path: "/preferences-demo"
      fullPath: "/preferences-demo"
      preLoaderRoute: typeof PreferencesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/gateway-config": {
      id: "/gateway-config"
      path: "/gateway-config"
      fullPath: "/gateway-config"
      preLoaderRoute: typeof GatewayConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/examples": {
      id: "/examples"
      path: "/examples"
      fullPath: "/examples"
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm-follow-ups": {
      id: "/crm-follow-ups"
      path: "/crm-follow-ups"
      fullPath: "/crm-follow-ups"
      preLoaderRoute: typeof CrmFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm-dashboard": {
      id: "/crm-dashboard"
      path: "/crm-dashboard"
      fullPath: "/crm-dashboard"
      preLoaderRoute: typeof CrmDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout": {
      id: "/checkout"
      path: "/checkout"
      fullPath: "/checkout"
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/billing": {
      id: "/billing"
      path: "/billing"
      fullPath: "/billing"
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm/pipeline": {
      id: "/crm/pipeline"
      path: "/crm/pipeline"
      fullPath: "/crm/pipeline"
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm/leads": {
      id: "/crm/leads"
      path: "/crm/leads"
      fullPath: "/crm/leads"
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm/contacts": {
      id: "/crm/contacts"
      path: "/crm/contacts"
      fullPath: "/crm/contacts"
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/crm/leads/$leadId": {
      id: "/crm/leads/$leadId"
      path: "/$leadId"
      fullPath: "/crm/leads/$leadId"
      preLoaderRoute: typeof CrmLeadsLeadIdRouteImport
      parentRoute: typeof CrmLeadsRoute
    }
    "/crm/contacts/$contactId": {
      id: "/crm/contacts/$contactId"
      path: "/$contactId"
      fullPath: "/crm/contacts/$contactId"
      preLoaderRoute: typeof CrmContactsContactIdRouteImport
      parentRoute: typeof CrmContactsRoute
    }
  }
}

interface CrmContactsRouteChildren {
  CrmContactsContactIdRoute: typeof CrmContactsContactIdRoute
}

const CrmContactsRouteChildren: CrmContactsRouteChildren = {
  CrmContactsContactIdRoute: CrmContactsContactIdRoute,
}

const CrmContactsRouteWithChildren = CrmContactsRoute._addFileChildren(
  CrmContactsRouteChildren,
)

interface CrmLeadsRouteChildren {
  CrmLeadsLeadIdRoute: typeof CrmLeadsLeadIdRoute
}

const CrmLeadsRouteChildren: CrmLeadsRouteChildren = {
  CrmLeadsLeadIdRoute: CrmLeadsLeadIdRoute,
}

const CrmLeadsRouteWithChildren = CrmLeadsRoute._addFileChildren(
  CrmLeadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  CheckoutRoute: CheckoutRoute,
  CrmDashboardRoute: CrmDashboardRoute,
  CrmFollowUpsRoute: CrmFollowUpsRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  GatewayConfigRoute: GatewayConfigRoute,
  PreferencesDemoRoute: PreferencesDemoRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UserPreferencesRoute: UserPreferencesRoute,
  UsersRoute: UsersRoute,
  CrmContactsRoute: CrmContactsRouteWithChildren,
  CrmLeadsRoute: CrmLeadsRouteWithChildren,
  CrmPipelineRoute: CrmPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
