/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as UsersRouteImport } from "./pages/users"
import { Route as UnauthorizedRouteImport } from "./pages/unauthorized"
import { Route as ExamplesRouteImport } from "./pages/examples"
import { Route as DashboardRouteImport } from "./pages/dashboard"
import { Route as AuthDemoRouteImport } from "./pages/auth-demo"
import { Route as AboutRouteImport } from "./pages/about"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: "/examples",
  path: "/examples",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDemoRoute = AuthDemoRouteImport.update({
  id: "/auth-demo",
  path: "/auth-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/auth-demo": typeof AuthDemoRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/users": typeof UsersRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/auth-demo": typeof AuthDemoRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/users": typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/auth-demo": typeof AuthDemoRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/users": typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/about"
    | "/auth-demo"
    | "/dashboard"
    | "/examples"
    | "/unauthorized"
    | "/users"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/about"
    | "/auth-demo"
    | "/dashboard"
    | "/examples"
    | "/unauthorized"
    | "/users"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/about"
    | "/auth-demo"
    | "/dashboard"
    | "/examples"
    | "/unauthorized"
    | "/users"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AuthDemoRoute: typeof AuthDemoRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UsersRoute: typeof UsersRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/examples": {
      id: "/examples"
      path: "/examples"
      fullPath: "/examples"
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth-demo": {
      id: "/auth-demo"
      path: "/auth-demo"
      fullPath: "/auth-demo"
      preLoaderRoute: typeof AuthDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AuthDemoRoute: AuthDemoRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
