/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as UsersRouteImport } from "./pages/users"
import { Route as UserPreferencesRouteImport } from "./pages/user-preferences"
import { Route as PreferencesDemoRouteImport } from "./pages/preferences-demo"
import { Route as ExamplesRouteImport } from "./pages/examples"
import { Route as DashboardRouteImport } from "./pages/dashboard"
import { Route as AboutRouteImport } from "./pages/about"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any)
const UserPreferencesRoute = UserPreferencesRouteImport.update({
  id: "/user-preferences",
  path: "/user-preferences",
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesDemoRoute = PreferencesDemoRouteImport.update({
  id: "/preferences-demo",
  path: "/preferences-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: "/examples",
  path: "/examples",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/about": typeof AboutRoute
  "/dashboard": typeof DashboardRoute
  "/examples": typeof ExamplesRoute
  "/preferences-demo": typeof PreferencesDemoRoute
  "/user-preferences": typeof UserPreferencesRoute
  "/users": typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/about"
    | "/dashboard"
    | "/examples"
    | "/preferences-demo"
    | "/user-preferences"
    | "/users"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/about"
    | "/dashboard"
    | "/examples"
    | "/preferences-demo"
    | "/user-preferences"
    | "/users"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/about"
    | "/dashboard"
    | "/examples"
    | "/preferences-demo"
    | "/user-preferences"
    | "/users"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  PreferencesDemoRoute: typeof PreferencesDemoRoute
  UserPreferencesRoute: typeof UserPreferencesRoute
  UsersRoute: typeof UsersRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/user-preferences": {
      id: "/user-preferences"
      path: "/user-preferences"
      fullPath: "/user-preferences"
      preLoaderRoute: typeof UserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preferences-demo": {
      id: "/preferences-demo"
      path: "/preferences-demo"
      fullPath: "/preferences-demo"
      preLoaderRoute: typeof PreferencesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/examples": {
      id: "/examples"
      path: "/examples"
      fullPath: "/examples"
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  PreferencesDemoRoute: PreferencesDemoRoute,
  UserPreferencesRoute: UserPreferencesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
